[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "7UqgJED9LZXYUbAbmo3BSryr21CDzPcUUWkW8X85gV4C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/gavinfowler/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
